@startuml

skinparam svgLinkTarget _top
skinparam hyperlinkUnderline false
skinparam agent {
	FontColor #111111
	BorderThickness 2
	BackgroundColor<<HealthcareService>> #FFF5E6
	BorderColor<<HealthcareService>> #D48806
	BackgroundColor<<Location>> #FFE2C2
	BorderColor<<Location>> #CC5200
	BackgroundColor<<Network>> #BFDBFE
	BorderColor<<Network>> #1E40AF
	BackgroundColor<<Organization>> #EEFBEF
	BorderColor<<Organization>> #2E7D32
	BackgroundColor<<OrganizationAffiliation>> #FCEBFF
	BorderColor<<OrganizationAffiliation>> #A21CAF
}

agent OrganizationAffiliation as orgAff <<OrganizationAffiliation>> [[StructureDefinition-ndh-OrganizationAffiliation.html{NDH OrganizationAffiliation profile}]]
agent Organization as organization1 <<Organization>> [[StructureDefinition-ndh-Organization.html{NDH Organization profile}]]
agent Organization as organization2 <<Organization>> [[StructureDefinition-ndh-Organization.html{NDH Organization profile}]]
agent Location as location <<Location>> [[StructureDefinition-ndh-Location.html{NDH Location profile}]]
agent Organization as network <<Network>> [[StructureDefinition-ndh-Network.html{NDH Network profile}]]
agent HealthcareService as service <<HealthcareService>> [[StructureDefinition-ndh-HealthcareService.html{NDH HealthcareService profile}]]


orgAff -right-> organization2: "participating organization 0..1"
orgAff -up-> organization1:  "organization 0..1"
orgAff -down-> service: "healthcare services 0..*"
orgAff -down-> network: "networks 0..*"
orgAff -left-> location: "locations 0..*"

@enduml